typography_spectrum: 0.10338
color:
  brandColors:
    - '#02489d'
    - '#000000'
    - '#fefefe'
    - '#6f716e'
    - '#85c5f3'
  brandStrength: 1
  lightness: 0.8125
  saturation: 0.0625
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.327
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Heather Klug
  email: heather@onedeterminedgirl.com
  url: www.onedeterminedigirl.com
name: 'One Determined Girl '
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/df4a5c87-d29b-4338-923c-4b7706199ab0.ico
title: One Determined Girl | Lifestyle Redesign & Coaching
description: Specializing in second chances and unlimited do-overs!
purpose: []
