name: 'One Determined Girl '
favicon: null
layout_spectrum: 0.572395739145577
typography_spectrum: 0.3669883378315717
title: 'One Determined Girl | Lifestyle Redesign & Coaching'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6964739870745689
  lightness: 0.49415382207371294
  saturation: 0.5470877457410097
  rhythmicContrast: 0.8687126294244081
purpose: []
