name: 'One Determined Girl '
favicon: null
layout_spectrum: 0.327
typography_spectrum: 0.16667
title: 'One Determined Girl | Lifestyle Redesign & Coaching'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#02489d'
    - '#000000'
    - '#fefefe'
    - '#6f716e'
    - '#85c5f3'
  brandStrength: 0.6964739870745689
  lightness: 0.6875
  saturation: 0.0625
  rhythmicContrast: 0.75
purpose: []
