typography_spectrum: 0.10338
color:
  brandColors:
    - '#02489d'
    - '#000000'
    - '#fefefe'
    - '#6f716e'
    - '#85c5f3'
  brandStrength: 1
  lightness: 0.8125
  saturation: 0.0625
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.327
analytics:
  google: null
  facebook: null
  twitter: null
name: 'One Determined Girl '
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: One Determined Girl | Lifestyle Redesign & Coaching
description: Specializing in second chances and unlimited do-overs!
purpose: []
